name: m4m
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  assets_audio_player: ^3.0.6
  audio_video_progress_bar: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  hive_flutter: ^1.1.0
  marquee: ^2.2.3
  on_audio_query: ^2.6.1
  package_info_plus: ^3.0.3
  permission_handler: ^10.2.0
  rate_my_app: ^1.1.3
  share_plus: ^6.3.1
  top_snackbar_flutter: ^3.0.0+1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  color: "#E0E0E0"
  color_dark: "#3700b3"
  image: assets/images/splash_screen_white.png
  image_dark: assets/images/splash_screen_white.png
  android: true
  ios: true
flutter:
  uses-material-design: true

  assets:
    - assets/
    # - assets/images
